"""
Phase 6 – ORM Model: ConsolidatedEvaluation
Table: consolidated_evaluations
Stores final consolidated marks, feedback, agreement level, and status per question.
"""
from __future__ import annotations

import uuid
from sqlalchemy import DateTime, Float, Index, String, Text, func, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class ConsolidatedEvaluation(Base):
    """
    Consolidated Evaluation output generated by Phase 6 Consensus Engine.
    Consumes Phase 5 reports and assigns final normalized marks and consolidated feedback.
    """
    __tablename__ = "consolidated_evaluations"

    consolidated_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    student_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    evaluation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_identity.evaluation_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    blueprint_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    question_id: Mapped[str] = mapped_column(String(255), nullable=False)
    question_number: Mapped[str] = mapped_column(String(50), nullable=False)
    maximum_marks: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Agent Scores
    accuracy_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    completeness_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    depth_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    weighted_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Final Marks & Percentage
    final_marks: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    percentage: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Consensus & Agreement Metrics
    agreement_level: Mapped[str] = mapped_column(String(50), nullable=False, default="High Agreement")
    evaluation_confidence: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    evaluation_status: Mapped[str] = mapped_column(String(50), nullable=False, default="Good")

    # Consolidated Feedback Lists
    strengths: Mapped[list | None] = mapped_column(JSONB().with_variant(JSON, "sqlite"), nullable=True)
    weaknesses: Mapped[list | None] = mapped_column(JSONB().with_variant(JSON, "sqlite"), nullable=True)
    missing_concepts: Mapped[list | None] = mapped_column(JSONB().with_variant(JSON, "sqlite"), nullable=True)
    improvement_suggestions: Mapped[list | None] = mapped_column(JSONB().with_variant(JSON, "sqlite"), nullable=True)
    final_remarks: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[object] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[object] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("ix_ce_eval_qno", "evaluation_id", "question_number"),
    )
