import React from 'react';
import { Activity, ArrowUpRight, CheckCircle2, ClipboardCheck, FileCheck2, FileText, Plus, UploadCloud } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, MetricCard, PageHeader, ProgressBar, StatusBadge } from '../components/ui';

const activity = [{ title: 'Answer sheet batch uploaded', detail: 'CS8451 · 24 files', time: '12 min ago', status: 'Completed', icon: UploadCloud }, { title: 'OCR processing completed', detail: '18 of 18 pages processed', time: '38 min ago', status: 'Completed', icon: FileText }, { title: 'Review queue updated', detail: '4 sheets need attention', time: '1 hr ago', status: 'Needs review', icon: ClipboardCheck }, { title: 'Blueprint generated', detail: 'Database Management Systems', time: 'Yesterday', status: 'Completed', icon: FileCheck2 }];

export default function Dashboard() {
  return <div className="page-container"><PageHeader eyebrow="Wednesday, July 22, 2026" title="Good morning, Alex" description="Here’s what’s happening across your evaluation workspace today." actions={<Link className="primary-button" to="/answer-sheets"><Plus size={17} /> New upload</Link>} />
    <div className="metric-grid"><MetricCard label="Total answer sheets" value="1,284" change="↑ 12.4% this month" icon={FileText} /><MetricCard label="OCR success rate" value="96.8%" change="↑ 2.1% this month" icon={Activity} tone="yellow" /><MetricCard label="Pending manual reviews" value="24" change="4 high priority" icon={ClipboardCheck} tone="yellow" /><MetricCard label="Question papers processed" value="86" change="↑ 8 this month" icon={FileCheck2} /></div>
    <div className="dashboard-grid"><Card title="Processing overview" description="Evaluation pipeline activity for the last 30 days" action={<button className="text-button">Last 30 days <ArrowUpRight size={14} /></button>}><div className="chart-area"><div className="chart-summary"><strong>1,284</strong><span>Sheets processed</span><StatusBadge status="+12.4%" /></div><div className="chart"><div className="chart-y"><span>1.5k</span><span>1k</span><span>500</span><span>0</span></div><div className="chart-bars">{[42, 58, 48, 73, 61, 82, 68, 91, 75, 84, 71, 96].map((height, i) => <div className="bar-column" key={i}><span className="bar" style={{ height: `${height}%` }} /><small>{['Jun 25', '', 'Jul 02', '', 'Jul 09', '', 'Jul 16', '', 'Today', '', '', ''][i]}</small></div>)}</div></div></div></Card>
      <Card title="Pipeline health" description="Current system status"><div className="health-list"><div><span className="health-label"><i className="health-dot green" />OCR engine</span><strong>Operational</strong></div><div><span className="health-label"><i className="health-dot green" />Blueprint engine</span><strong>Operational</strong></div><div><span className="health-label"><i className="health-dot yellow" />Manual review queue</span><strong>24 pending</strong></div><ProgressBar value={96.8} label="Overall success rate" /></div></Card></div>
    <div className="dashboard-grid lower"><Card title="Recent activity" description="Latest events from your workspace" action={<button className="text-button">View all <ArrowUpRight size={14} /></button>}><div className="activity-list">{activity.map(({ title, detail, time, status, icon: Icon }) => <div className="activity-row" key={title}><span className="activity-icon"><Icon size={17} /></span><div className="activity-copy"><strong>{title}</strong><span>{detail}</span></div><div className="activity-meta"><StatusBadge status={status} /><small>{time}</small></div></div>)}</div></Card><Card title="Quick actions" description="Common tasks"><div className="quick-actions"><Link to="/answer-sheets" className="quick-action"><span className="quick-icon green"><UploadCloud size={18} /></span><span><strong>Upload answer sheets</strong><small>Process handwritten scripts</small></span><ArrowUpRight size={15} /></Link><Link to="/question-papers" className="quick-action"><span className="quick-icon yellow"><FileText size={18} /></span><span><strong>Upload question paper</strong><small>Build a new blueprint</small></span><ArrowUpRight size={15} /></Link><Link to="/manual-review" className="quick-action"><span className="quick-icon gray"><CheckCircle2 size={18} /></span><span><strong>Review queue</strong><small>4 items need attention</small></span><ArrowUpRight size={15} /></Link></div></Card></div>
  </div>;
}
