import React, { useEffect, useState } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { BookOpen, CheckCircle2, FileText, Sparkles } from 'lucide-react';
import { Card, FileUploader, PageHeader } from '../components/ui';

export default function QuestionPaperPage({ apiKey }) {
  const [paper, setPaper] = useState(null); const [answerKey, setAnswerKey] = useState(null); const [masters, setMasters] = useState([]); const [metadata, setMetadata] = useState({ exam_name: 'End Semester Examination', subject: '', subject_code: '', regulation: '', semester: '', department: '', duration_minutes: 180, maximum_marks: 100 }); const [loading, setLoading] = useState(false);
  useEffect(() => { axios.get('/api/academic-master', { params: { status: 'ACTIVE', page_size: 100 }, headers: apiKey ? { 'x-api-key': apiKey } : {} }).then((response) => { const records = response.data.items || []; setMasters(records); if (records[0]) setMetadata((current) => ({ ...current, subject: records[0].subject_name, subject_code: records[0].subject_code, regulation: records[0].regulation, semester: records[0].semester, department: records[0].department })); }).catch(() => toast.error('Academic master data could not be loaded.')); }, [apiKey]);
  const update = (key, value) => setMetadata({ ...metadata, [key]: value });
  const submit = async (event) => { event.preventDefault(); if (!paper) return toast.error('Please upload a question paper first.'); setLoading(true); const data = new FormData(); data.append('ocr_json', await paper.text().catch(() => '')); data.append('metadata', JSON.stringify(metadata)); if (answerKey) data.append('answer_key', answerKey); try { const headers = apiKey ? { 'x-api-key': apiKey } : {}; await axios.post('/blueprints', data, { headers }); toast.success('Question paper submitted for blueprint generation.'); } catch (error) { toast.error(error.response?.data?.detail || 'Question paper upload failed.'); } finally { setLoading(false); } };
  return <div className="page-container"><PageHeader eyebrow="Blueprints / New paper" title="Upload question paper" description="Add a question paper and optional answer key to generate a structured exam blueprint." /><form onSubmit={submit} className="form-layout"><Card title="Question paper" description="Upload the source document for OCR extraction."><FileUploader file={paper} onFile={setPaper} accept=".pdf,.png,.jpg,.jpeg,.txt,.json" label="Drop question paper here, or browse" hint="PDF, image, TXT, or JSON up to 25MB" /><div className="file-note"><BookOpen size={16} /><span>We’ll extract sections, questions, marks, and question types automatically.</span></div></Card><Card title="Exam metadata" description="Select a subject from the centralized Academic Master."><div className="form-grid"><label className="field full-field"><span>Subject</span><select value={metadata.subject_code} onChange={(e) => { const selected = masters.find((item) => item.subject_code === e.target.value); if (selected) setMetadata({...metadata, subject:selected.subject_name, subject_code:selected.subject_code, regulation:selected.regulation, semester:selected.semester, department:selected.department}); }} required><option value="">Select a subject</option>{masters.map((item) => <option key={item.id} value={item.subject_code}>{item.subject_code} · {item.subject_name}</option>)}</select></label>{[['exam_name','Exam name'],['subject_code','Subject code'],['regulation','Regulation'],['semester','Semester'],['department','Department'],['duration_minutes','Duration (minutes)'],['maximum_marks','Maximum marks']].map(([key,label]) => <label className="field" key={key}><span>{label}</span><input value={metadata[key]} readOnly={['subject_code','regulation','semester','department'].includes(key)} onChange={(e) => update(key, e.target.value)} required /></label>)}</div></Card><Card title="Faculty answer key" description="Optional mapping used to support answer evaluation."><FileUploader file={answerKey} onFile={setAnswerKey} accept=".pdf,.docx,.txt" label="Drop answer key here, or browse" hint="PDF, DOCX, or TXT · Optional" /><div className="form-submit"><span><Sparkles size={16} /> AI extraction is ready to run</span><button className="primary-button" disabled={loading}>{loading ? 'Generating…' : <><CheckCircle2 size={17} /> Generate blueprint</>}</button></div></Card></form></div>;
}
